<?php View::content(); ?>
<h3>Editar Platillo<h3>
 
<?php echo Form::open();?>
 
        <div>
        	<label>Nombre
	        <?php echo Form::text('menus.nombre') ?></label>
	 		<br>
	        <label>Categoría
	        <?php echo Form::text('menus.categoria') ?></label>
	 		<br>
			<label>Precio
	        <?php echo Form::text('menus.precio') ?></label>
	 		<br>
	        <?php echo Form::hidden('menus.id') ?>
	        <?php echo Form::submit('Actualizar') ?>
        </div>
 
<?php echo Form::close() ?>