<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <header >
    <nav>
      <div ALIGN=center >
        <ul>
          <li style="display:inline;"><?php echo Html::link('menus/', 'Mostrar Menú') ?></li>
          <li style="display:inline;"><?php echo Html::link('menus/create', 'Crear Nuevo Platillo') ?></li>                
        </ul>
      </div>
    </nav>
  </header>
<body>
    <div id='content'>
        <?php View::content(); ?>
    </div>
</body>
</html>
